# Generated by Django 5.2.5 on 2025-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publish_year', models.IntegerField()),
                ('cover_image', models.URLField()),
                ('category', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('SCI', 'Science'), ('TECH', 'Technology'), ('BIO', 'Biography'), ('OTH', 'Other')], max_length=50)),
            ],
        ),
    ]
